export const SET_CURRENT_DRAG_COMPONENT = "SET_CURRENT_DRAG_COMPONENT";
export const SET_CURRENT_DRAG_COMPONENT_BY_COMPONENT_LIST =
  "SET_CURRENT_DRAG_COMPONENT_BY_COMPONENT_LIST";
export const SET_COMPONENT_LIST = "SET_COMPONENT_LIST";
export const DEL_COMPONENT_LIST = "DEL_COMPONENT_LIST";
export const COPY_COMPONENT_LIST = 'COPY_COMPONENT_LIST'
export const INSERT_COMPONENT_LIST = "INSERT_COMPONENT_LIST";
export const UPDATE_COMPONENT_LIST_BY_CURRENT_DRAG =
  "UPDATE_COMPONENT_LIST_BY_CURRENT_DRAG";
export const UPDATE_COMPONENT_LIST_AND_CURRENT_DRAG =
  "UPDATE_COMPONENT_LIST_AND_CURRENT_DRAG";
export const DELETE_ALL_COMPONENT_LIST_AND_CURRENT_DRAG =
  "DELETE_ALL_COMPONENT_LIST_AND_CURRENT_DRAG";
export const UPDATE_COMPONENT_LIST_OF_ITEM_CHILDREN =
  "UPDATE_COMPONENT_LIST_OF_ITEM_CHILDREN";
