tasks:
  - init: yarn install
    command: |
      export CLIENT_URL="$(gp url 35729)/livereload.js?snipver=1&port=443"
      { gp await-port 3000 && sleep 5 && gp preview $(gp url 5000) & } &> /dev/null
      gp open src/react-visual-editor.tsx
      yarn start
ports:
  - port: 3000
    onOpen: ignore
  - port: 35729
    onOpen: ignore
vscode:
  extensions:
  # - svelte.svelte-vscode
