export const CONTENT_MENU_CLICK = "CONTENT_MENU_CLICK";

export const SHOW_SETTING_PANL = "SHOW_SETTING_PANL";

export const SCROLL_CENTER = "SCROLL_CENTER";
export const INFINITEVIEWER_SCROLL = "INFINITEVIEWER_SCROLL";