export const SET_TARGET = "SET_TARGET";
export const DELETE_TARGET = "DELETE_TARGET";
export const SET_TARGET_BY_COMPONENT_LIST = "SET_TARGET_BY_COMPONENT_LIST";
export const SET_COMPONENT_LIST = "SET_COMPONENT_LIST";
export const PUT_COMPONENT_LIST = "PUT_COMPONENT_LIST";
export const DEL_COMPONENT_LIST = "DEL_COMPONENT_LIST";
export const COPY_COMPONENT_LIST = "COPY_COMPONENT_LIST";
export const INSERT_COMPONENT_LIST = "INSERT_COMPONENT_LIST";
export const UPDATE_COMPONENT_LIST_BY_TARGET = "UPDATE_COMPONENT_LIST_BY_TARGET";
export const UPDATE_COMPONENT_LIST_AND_TARGET = "UPDATE_COMPONENT_LIST_AND_TARGET";
export const DELETE_ALL_COMPONENT_LIST_AND_TARGET =
  "DELETE_ALL_COMPONENT_LIST_AND_TARGET";
export const UPDATE_COMPONENT_LIST_OF_ITEM_CHILDREN =
  "UPDATE_COMPONENT_LIST_OF_ITEM_CHILDREN";
export const SET_MOVEABLE_OPTIONS = "SET_MOVEABLE_OPTIONS";
export const RESET_COMPONENT_LAYOUT = "RESET_COMPONENT_LAYOUT";
